############----INGRESS---#####################################
{{- range $key, $value := $.Values.oneuptime.hosts }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/part-of: oneuptime
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ printf "%s" $.Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "balanced"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "false"
    nginx.ingress.kubernetes.io/session-cookie-name: "fi-ingress-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  name: {{ printf "%s-%s-%s" $.Release.Name $key "ingress"  }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $value.tls.enabled }} 
  tls:
    - hosts:
      - {{ $value.host }}
      secretName: {{ printf "%s-%s-%s" $.Release.Name $key "tls"  }}
  {{- end }}
  rules:
    {{- if $value.host }} 
    - host: {{ $value.host }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /accounts
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "accounts"  }}
              servicePort: 80
          - path: /data-ingestor
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "ingestor"  }}
              servicePort: 80
          - path: /probe-api
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "probe-api"  }}
              servicePort: 80
          - path: /dashboard
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "dashboard"  }}
              servicePort: 80
          - path: /admin
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "admin"  }}
              servicePort: 80
          - path: /api
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "backend"  }}
              servicePort: 80
          - path: /realtime
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "realtime" }}
              servicePort: 80
          - path: /status-page
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "status"  }}
              servicePort: 80
          - path: /haraka
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "haraka"  }}
              servicePort: 80
          - path: /application
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "app-scan"  }}
              servicePort: 80
          - path: /container
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "cont-scan"  }}
              servicePort: 80
          - path: /lighthouse
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "lighthouse"  }}
              servicePort: 80
          - path: /script
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "script"  }}
              servicePort: 80
          {{- range $probeKey, $probeValue := $.Values.probes }}
          - path: {{ printf "/%s" $probeKey }}
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name $probeKey }}
              servicePort: 80
          {{- end }}
          {{- if $.Values.saas.isSaasService }}
          - path: /
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "home"  }}
              servicePort: 80
          - path: /docs
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "api-docs"  }}
              servicePort: 80
          - path: /license
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "licensing"  }}
              servicePort: 80
          - path: /chart
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "helm-chart"  }}
              servicePort: 80
          {{- else }}
          - path: /
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "accounts"  }}
              servicePort: 80
          {{- end }}
          {{- if $.Values.saas.exposeInitScriptContainer }}
          - path: /
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "init-script"  }}
              servicePort: 80
          {{- end }}   
---
{{- end }}
##########################################################################
