##################################################################################  
## Important: If you're implenting this in the enterprise environment, this should always be `false`. 
## This is for Fyipe SaaS service. This will deploy all the SaaS env vars
################################################################################## 
saas: 
  isSaasService: false
  stripe: 
    publicKey: #Stripe public and private key
    privateKey: 
  airtable: 
    key: #Airtbale key to store leads. 
    baseId: 
  amplitude: 
    key: #Amplitude for tracking. 
  licensing:
    airtable: # Airtable for validating licenses. 
      key: 
      baseId: 
    tokenSecret: # Encrypting lisense with tokens to send them to clients. 

###################################################################################

statusPage: 
  hosts:
    host1: 
      host: 
      tls:
        enabled: false
        crt: 
        key:
  cert: # certificate for a custom domain
  key: # private key for a custom domain

##################################################################################  
## Important: Fyipe Values. More information in the Readme.md 
################################################################################## 
fyipe:
  admin: 
    email: 
    password: 
  hosts:
    host1: 
      host: 
      tls:
        enabled: false
        crt: 
        key: 
  licensingUrl: https://fyipe.com/license

###################################################################################

httpTestServer: 
    hosts:
      host1: 
        host: 
        tls:
          enabled: false
          crt: 
          key: 

##################################################################################  
## Important: Probe Values. More information in the Readme.md 
################################################################################## 

probes:
  probe1: 
    port: 3024
    name: Probe 1
    key: sample-key
    servicePort: 80
  probe2: 
    name: Probe 2
    port: 3025
    key: sample-key
    servicePort: 80

##################################################################################  
## Important: RateLimitter Values. More information in the Readme.md 
################################################################################## 

rateLimitter:
  enabled: false
  requestLimit: 5000
  requestLimitTimePeriodInMS: 216000


## Fyipe official image version on Docker Hub
## ref: https://hub.docker.com/u/fyipeproject
##

image:
  registry: docker.io
  repository: fyipeproject
  tag: latest
  pullPolicy: Always
  restartPolicy: Always

replicaCount: 1

##################################################################################
## IMPORTANT: 
## Values for Subcharts
##

redis: 
  redisPort: 6379
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: latest
    pullPolicy: Always
  usePassword: false
  persistence:
    enabled: true
    mountPath: /bitnami/mongodb
    size: 20Gi


mongodb: 
  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: latest
    pullPolicy: Always
  mongodbRootPassword: root
  mongodbUsername: fyipe
  mongodbPassword: password
  mongodbDatabase: fyipedb
  replicaSet:
    enabled: true
    name: rs0
    useHostnames: true
    key: mongodbfyipe
    secondary: 1
    arbiter: 1
  persistence:
    enabled: true
    mountPath: /bitnami/mongodb
    size: 1000Gi
  useStatefulSet: true

# mongodb: 
#   architecture: replicaset
#   image:
#     registry: docker.io
#     repository: bitnami/mongodb
#     tag: latest
#     pullPolicy: Always
#   arbiter: 
#     enabled: true
#   auth: 
#     enabled: true
#     rootPassword: root
#     username: fyipe
#     password: password
#     database: fyipedb
#     replicaSetKey: mongodbfyipe
#   replicaSetName: rs0
#   replicaCount: 2
#   replicaSetHostnames: true
#   persistence:
#     enabled: true
#     mountPath: /bitnami/mongodb
#     size: 20Gi
#   useStatefulSet: true

## Service Configuration
## For minikube, set service.type to NodePort, elsewhere use LoadBalancer
##

ingress-nginx:
  ingressClass: k8s.io/ingress-nginx
  service: 
    type: LoadBalancer
  defaultBackend:
    enabled: false
  proxySetHeaders:
    X-Forwarded-For: $http_x_forwarded_for
    X-Real-Ip: $http_x_forwarded_for
  config:
    log-format-upstream: '$remote_addr - $http_cf_connecting_ip - $http_x_forwarded_for - $request_id - [$proxy_add_x_forwarded_for] - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status'
    proxy-protocol: "true"
    real-ip-header: "X-Forwarded-For"

  ##################################################################################

haraka:
  fromEmail:
  fromName: 
  user: 
  password:
  domain:
  # This should be base64 of your private key
  dkimPrivateKey:
  tlsCert:
  tlsKey:

host: 
  backendPort: 3002
  homePort: 1444
  licensingPort: 3004
  statusPagePort: 3006
  dashboardPort: 3000
  accountsPort: 3003
  helmChartPort: 3423
  apiDocsPort: 1445
  # if port 25 is avaialble and accessible
  # then we can use it as default port
  harakaPort: 2525
  httpTestServerPort: 3010
  adminDashboardPort: 3100
  backendServicePort: 80
  homeServicePort: 80
  apiDocsServicePort: 80
  statusPageServicePort: 80
  dashboardServicePort: 80
  accountsServicePort: 80
  adminDashboardServicePort: 80
  backendNodePort: 80
  statusPageNodePort: 80
  dashboardNodePort: 80
  accountsNodePort: 80
  adminDashboardNodePort: 80
  licensingServicePort: 80
  helmChartServicePort: 80
  httpTestServerServicePort: 80
  harakaServicePort: 2525

isThirdPartyBilling: false
isRunningOnGCPMarketplace: false
isTesting: false

# Encryption Key
encryptionKey: ThisEncryptionKeyLengthIs32Size.

# If you disable sign up, then you need to specify 
# fyipe.admin.email and fyipe.admin.password values for the admin account. 
disableSignup: false

# What protocol is backend running on. Takes in values like 'http:' or 'https:'
backendProtocol: 

# Status page domain to add to CNAME to work with custom domains
statusPageDomain:

# Push notificaitons. 
# Generate public and pivate key for push notifications. 
# These are just the test keys. 
# You can generate them by: 
# First install the web-push npm package using npm install web-push -g, then run web-push generate-vapid-keys

pushNotification:
    publicKey: "BD1kb-OchZlXr32bmwpjhoxp_cq-aqK4dWXRDkC5m6Hd9_cvMOUw_bXRFR3pJFGzpEdjQUk5SDdYaXvb7xd-1Dg"
    privateKey: "WdFZTeXkuoxpsO_KNOtXvhDUc_Ae1rb-WjPv6AVexA4"
    url: "https://fyipe-test.com"