##################################################################################  
## Important: If you're implenting this in the enterprise environment, this should always be `false`. 
## This is for Fyipe SaaS service. This will deploy all the SaaS env vars
################################################################################## 
saas: 
  isSaasService: false
  stripe: 
    publicKey: #Stripe public and private key
    privateKey: 
  airtable: 
    key: #Airtbale key to store leads. 
    baseId: 
  amplitude: 
    key: #Amplitude for tracking. 
  licensing:
    airtable: # Airtable for validating licenses. 
      key: 
      baseId: 
    tokenSecret: # Encrypting lisense with tokens to send them to clients. 
  support: 
    slackToken: # Slack token for Fyipe-help workspace

###################################################################################

statusPage: 
  hosts:
    host1: 
      host: 
      tls:
        enabled: false
        crt: 
        key: 

##################################################################################  
## Important: Fyipe Values. More information in the Readme.md 
################################################################################## 
fyipe:
  admin: 
    email: 
    password: 
  hosts:
    host1: 
      host: 
      tls:
        enabled: false
        crt: 
        key: 
  licensingUrl: https://fyipe.com/license

##################################################################################  
## Important: Probe Values. More information in the Readme.md 
################################################################################## 

probes:
  probe1: 
    port: 3024
    name: Probe 1
    key: sample-key
    servicePort: 80
  probe2: 
    name: Probe 2
    port: 3025
    key: sample-key
    servicePort: 80

##################################################################################  
## Important: RateLimitter Values. More information in the Readme.md 
################################################################################## 

rateLimitter:
  enabled: false
  requestLimit: 5000
  requestLimitTimePeriodInMS: 216000


## Fyipe official image version on Docker Hub
## ref: https://hub.docker.com/u/fyipeproject
##
image:
  registry: docker.io
  repository: fyipeproject
  tag: latest
  pullPolicy: Always
  restartPolicy: Always

replicaCount: 1

##################################################################################
## IMPORTANT: 
## Values for Subcharts
##

redis: 
  redisPort: 6379
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: latest
    pullPolicy: Always
  usePassword: false
  persistence:
    enabled: true
    mountPath: /bitnami/mongodb
    size: 20Gi


mongodb: 
  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: latest
    pullPolicy: Always
  mongodbRootPassword: root
  mongodbUsername: fyipe
  mongodbPassword: password
  mongodbDatabase: fyipedb
  replicaSet:
    enabled: true
    name: rs0
    useHostnames: true
    key: mongodbfyipe
    secondary: 1
    arbiter: 1
  persistence:
    enabled: true
    mountPath: /bitnami/mongodb
    size: 20Gi
  useStatefulSet: true

## Service Configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer
##
nginx-ingress-controller:
  service:
    type: LoadBalancer

  ##################################################################################

host: 
  backendPort: 3002
  homePort: 1444
  slackPort: 1267
  licensingPort: 3004
  statusPagePort: 3006
  dashboardPort: 3000
  accountsPort: 3003
  helmChartPort: 3423
  apiDocsPort: 1445
  adminDashboardPort: 3100
  backendServicePort: 80
  homeServicePort: 80
  apiDocsServicePort: 80
  slackServicePort: 80
  statusPageServicePort: 80
  dashboardServicePort: 80
  accountsServicePort: 80
  adminDashboardServicePort: 80
  backendNodePort: 80
  statusPageNodePort: 80
  dashboardNodePort: 80
  accountsNodePort: 80
  adminDashboardNodePort: 80
  licensingServicePort: 80
  helmChartServicePort: 80

isThirdPartyBilling: false
isRunningOnGCPMarketplace: false
isTesting: false