############----TEST-SERVER-INGRESS--#####################################
{{- if .Values.saas.isSaasService }} 
{{- range $key, $value := $.Values.httpTestServer.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
  name: {{ printf "%s-%s-%s" $.Release.Name $key "test"  }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: fyipe
    app.kubernetes.io/managed-by: helm
spec:
  {{- if  $value.tls.enabled }} 
  tls:
    - hosts:
      - {{  $value.host }} 
      secretName: {{ printf "%s-%s-%s" $.Release.Name $key "testtls"  }}
  {{- end }}
  rules:
    {{- if  $value.host }} 
    - host: {{  $value.host }} 
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "test"  }}
              servicePort: 80
---
{{- end }}
{{- end }}
##################################