############----STATUS-PAGE-INGRESS--#####################################
{{- if .Values.fyipe.hosts.host1.host }} 
{{- range $key, $value := $.Values.statusPage.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
  name: {{ printf "%s-%s-%s" $.Release.Name $key "statuspage"  }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if  $value.tls.enabled }} 
  tls:
    - hosts:
      - {{  $value.host }} 
      secretName: {{ printf "%s-%s-%s" $.Release.Name $key "statuspagetls"  }}
  {{- end }}
  rules:
    {{- if  $value.host }} 
    - host: {{  $value.host }} 
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            backend:
              serviceName: {{ printf "%s-%s" $.Release.Name "status-page"  }}
              servicePort: 80
---
{{- end }}
{{- end }}
##################################