##################################################################################
## Important: If you're implenting this in the enterprise environment, this should always be `false`.
## Is this Fyipe SaaS service. This will deploy all the SaaS env vars

##

saas:
    isSaasService: true
    slackErrorLog:
        webhook: https://hooks.slack.com/services/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
        channel: fyipe-logs
    stripe:
        publicKey: pk_test_UynUDrFmbBmFVgJXd9EZCvBj00QAVpdwPv
        privateKey: sk_test_YxwnzywggtAd8jDaHecNmHiN
    airtable:
        key: keye3gzJRafDIhRKg
        baseId: appgek0ngJaHhppeJ
    amplitude:
        key: 4b76c47248f969446af69dfdbf687d90
    licensing:
        airtable:
            key: keye3gzJRafDIhRKg
            baseId: appksCeuKfCS0e8fR
        tokenSecret: LicenseTokenSecret

httpTestServer:
    hosts:
        host1:
            host: staging-test-server.fyipe.com
            tls:
                enabled: false
                crt:
                key:
fyipe:
    hosts:
        host1:
            host: staging.fyipe.com
            tls:
                enabled: false
                crt:
                key:
    licensingUrl: https://fyipe.com/license

image:
    registry: docker.io
    repository: fyipeproject
    tag: master
    pullPolicy: Always
    restartPolicy: Always

replicaCount: 1

# This should be 32 chars in length.
encryptionKey: pg#K^C$-)IGOg6DYXDGq2jdmfws0MiR7

# Is backend on HTTPS?
backendProtocol: 'https'

haraka:
    fromEmail: 'noreply@fyipeapp.com'
    fromName: 'Fyipe Staging'
    domain: 'fyipeapp.com'
    user: 'noreply@fyipeapp.com'
    password: 'tX8z_bDEcRdRHnyKxAHYEQk_B'
    dkimPrivateKey: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBd0U0R1hxai9lODQ4VW1mNkttN0xsQUliZnpFTG5VbmdHQVc0NXBhYzhKelZoNzRNCmloVWZPZnB5cGNJVXZHSnFOaHRuSHJnRHE1Wk9QQTlNc2pFM1drYXQyZ2dUV0V2RFhDY3d0eHZVWnU3blpudkIKK3cxMzVRajNQeGZGVE1Tb1c4VWR5cHQ3UXlpRUhpVXVPZGNrVFhKM2sra1U5Qk41OVgxNmhPQlJtN2JkcnNNagpNQlEvNUQ3VHRjMGJ5TjBnd2dBUit6OXhueFFQWWpwNEtmaE1XWUxXRjFLTHdPQUZoZ1E4eFp3ZFZjTkY4aWl3CmF3a3FIYWx5VFg4SnFZNFRBamVXYW1icXdvQlN4V09nT2w4d1pSS2pPZFNhRmdEdHRRVDBrMzE2QzZxVEw1NlEKbStUMThac3k4MkFYdEQydGhCMG44T3lrSjhnV1kzMVVaSjZRbndJREFRQUJBb0lCQVFDSVVBWjEzUWRVUkFsQQpSSkh3dUI2NEtKSkRJNG5mRVhtMnJYKzJlL1o5SEQ3RC9MUTR3T1lrbStIZW0yZEZiZUZwdnh6bWludVhpbkNrClpCZnlpNjUzNEhmbGdDbnVRYTRXU1hWZnBtdDJGMHlSdVpIMEdrVHRaZUNVcVkzaWI5Z0RUUU5rRmJoWEQ0WXYKTkIzRFJEeG9aWVpib3pHR0hiUXFqcXBsTy9pOURiVWNlWmRoVlpEdlhFb21OTjBxYkNCZFhyN3lQcDBySXJqVwpjVXFxS1JSU1cyOU8vWndKeGt3Q1pwRTEvRHZDMjNpOUFpZWU1M1RMMTE4YTA5SDhrSmQ4YjBMYlpTZWhqWGVOCjB0c0h3dzhwNVY1eW93RjlnN3NmM0hhalRzSUd2eG5mWUNVMS9Dby9HQ3FyeW1IKzNLK3VOY0YwNHJ6aGluZmQKVDNHMWo0azVBb0dCQU9Cb0c1aWVZSkYyQkQ0elJnRVV5REFiS3pscGtqclN0YWh5eThxbnd5S2FLcjRVbzh5YQpPUFE3UVFuSnR1TkwwN1NVM211RmJKa2prTXNFbWYvTkdNSWlQOWd6cEdYeHZpcTlIM2t3SnlNZTVMYm5rYzZRCkpPSE5zKzBQN1FzZWlVUVZHSHBhc2FQR01hcXZ1dnIzMzNUYks3OEJIWXc2ak5SZU1qbFV2bm5sQW9HQkFOdGcKN1BkTHZQdGg3WDN0UTcxRjl4YjNCR1FBUmdIWTUvNWVZUFNjWGxCOFBkWk1abG95dkZuaGVpcjVUdlpMajhMSQpKTEw3NmJxYWF4OGJ4MmNueFJydUxtYnl2YmdGeUN4cFpVNUVhc1J2RDNhcTY1T0padGRacGtRcEdTUWgxWFl4CnB2R3Q3TGpWS1c3WlhYbGxwR3RVMjdNVjE4SHhDWlp2V0dSVkZxZ3pBb0dBRHcxc3JIUVRMaTZvWWpPMlFtUk8KZVV1WlBxU2lObWZqMzRTenZzZzZBcHdzdWN0UW9XekczVHNNUmNmT0NMa1JYaytPQzlCTFZJcGFNQVFEQUhHVgpjNUF3a0NRR3B2L3NMWm01L3JzSUpRYnhlSU5YK0c4YXlqcXVFdnk2ZmNCeW5LcDlsZGQzaXZERWJCcVZoRGdVCk9SWnFmTWxxWGZtZmNLOVExeCtrRnpFQ2dZRUFucHdpVjkyYmdnallZMzVpeG5yS1hnRTBYSFRTS00zQlZlaTQKb3NKWGNrdVJqZG5vK25mS05CWFFkVGVSUG9OOUtpLzRVS3ZQM2dsOVA1MmUrdGNITENSZXlqSGd0eWIvQmhVaAptSWZneGFzaWZBS3hsaGIya3VhUFRxS0VPZHA0Y2g4Tis1aHJHV3VNckVkZHpNS1BNTWJHbldGQ2dFY2NUbmFzCmFzWVdQbjhDZ1lFQWswVVNzWWtwekpRSGV1TTBVaHpnZkQyTXZmQm9LMjV6OFMvWkRlSnJUVFUwTjBQUTBVdi8KNTNvd0Yxd3Q2NWFjZjRJUFg3VElsZ3lZc2dFcVpFZWRDUU90a05LbkNjRFNVVnVLcWNqQW9MdUJzeThrZkVFUwphaFY0dzBkdFhaUnRJeWErRExaYlkwU0lGaWU5dVdTN0FqTnJONjJBUGVrWlhxcHlmblZ3ZDE4PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo='
