name: Common Jobs

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   # excludes hotfix branches
      - 'release'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y curl gcc
      - run: sudo apt-get install -y build-essential
      - run: sudo apt-get install -y nodejs
      - run: npm install
      - run: npm run lint
      - name: Show how to fix lint
        if: ${{ failure() }}
        run: echo "Please run `npm run fix` in your root directory to fix the lint automatically."

