name: Lighthouse Runner Production Deploy

on:
  push:
    branches:
      - release
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUBPASSWORD: ${{secrets.DOCKERHUBPASSWORD}}
      DOCKERHUBUSERNAME: ${{secrets.DOCKERHUBUSERNAME}}
      CI_PIPELINE_ID: ${{github.run_number}}
     
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh

      - run: sudo docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        # Build and deploy LighthouseRunner.
      - run: sudo docker login --username $DOCKERHUBUSERNAME --password $DOCKERHUBPASSWORD
      - run: sudo docker buildx create --use
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/LighthouseRunner:4.0.$CI_PIPELINE_ID --push -f ./LighthouseRunner/Dockerfile .
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/LighthouseRunner:latest --push -f ./LighthouseRunner/Dockerfile .
      - run: chmod +x ./ci/scripts/deployment-setup.sh
      - run: bash ./ci/scripts/deployment-setup.sh
      - run: chmod +x ./ci/scripts/deployment-production-setup.sh
      - run: bash ./ci/scripts/deployment-production-setup.sh
      - run: kubectl set image deployment/fi-lighthouse fi-lighthouse=oneuptime/LighthouseRunner:4.0.$CI_PIPELINE_ID
        # Cleanup
      - run: chmod +x ./ci/scripts/deployment-cleanup.sh
      - run: ./ci/scripts/deployment-cleanup.sh
