name: Probe API Production Deploy

on:
  push:
    branches:
      - release
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUBPASSWORD: ${{secrets.DOCKERHUBPASSWORD}}
      DOCKERHUBUSERNAME: ${{secrets.DOCKERHUBUSERNAME}}
      CI_PIPELINE_ID: ${{github.run_number}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      DIGITAL_OCEAN_API_KEY: ${{secrets.DIGITAL_OCEAN_API_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh
      - run: chmod +x ./ci/scripts/version-setup.sh
      - run: ./ci/scripts/version-setup.sh

      - run: sudo docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        # Build and deploy probe-api.
      - run: sudo docker login --username $DOCKERHUBUSERNAME --password $DOCKERHUBPASSWORD
      - run: sudo docker buildx create --use
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/probe-api:4.0.$CI_PIPELINE_ID --push -f ./probe-api/Dockerfile .
      - run: sudo docker buildx build --platform linux/amd64,linux/arm64 --tag oneuptime/probe-api:latest --push -f ./probe-api/Dockerfile .
      - run: chmod +x ./ci/scripts/deployment-setup.sh
      - run: bash ./ci/scripts/deployment-setup.sh
      - run: chmod +x ./ci/scripts/deployment-production-setup.sh
      - run: bash ./ci/scripts/deployment-production-setup.sh
      - run: sudo kubectl set image deployment/fi-probe-api fi-probe-api=oneuptime/probe-api:4.0.$CI_PIPELINE_ID
        # Cleanup
      - run: chmod +x ./ci/scripts/deployment-cleanup.sh
      - run: ./ci/scripts/deployment-cleanup.sh
