name: Model Test

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   # excludes hotfix branches
      - 'release'
      - 'staging-release'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd Model && npm install && npm run test
  