name: Probe Test

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   # excludes hotfix branches
      - 'release'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
          node-version: 18.3.0
      - run: curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
      - run: echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ focal main' | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
      - run: sudo apt update
      - run: sudo apt-get install cloudflare-warp -y  
      - run: warp-cli --accept-tos connect
      - run: curl -6 www.google.com
      - run: cd Common && npm install
      - run: cd CommonServer && npm install
      - run: cd Probe && npm install && npm run test


